# Generated by Django 4.0.6 on 2022-08-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_shoppingcart_books_shoppingcartitem_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppingcartitem',
            table='shopping_cart_item',
        ),
    ]
