# Generated by Django 4.0.6 on 2022-08-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shoppingcartitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='price_must_be_gte_0.0'),
        ),
    ]
