# Generated by Django 4.0.6 on 2022-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shoppingcartitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='cant',
            field=models.IntegerField(default=1),
        ),
    ]
