# Generated by Django 4.0.6 on 2022-08-23 16:40

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_price_shoppingcartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=core.models.get_path)),
                ('adress_line_1', models.CharField(default='', max_length=255)),
                ('adress_line_2', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state_provice_region', models.CharField(default='', max_length=255)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='United States', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
