# Generated by Django 4.0.6 on 2022-08-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shoppingcartitem_cant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='cant',
            new_name='quantity',
        ),
    ]
