# Generated by Django 4.0.6 on 2022-08-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_picture_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
