# Generated by Django 4.0.7 on 2022-09-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_description_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
    ]
