# Generate a JWT token

POST http://localhost:80/api/v1/auth/login/
Content-type: application/json

#test user
{
  "username": "yagua",
  "password": "root"
}

# generate a new pair access-fresh tokens

POST http://localhost:80/api/v1/auth/jwt/refresh/
Content-type: application/json

{
  "refresh": "{{REFRESH_TOKEN}}"
}


# validate JWT access token

POST http://localhost:80/api/v1/auth/jwt/verify/
Content-type: application/json

{
  "token": "{{ACCESS_TOKEN}}"
}
