### Get all Books

GET http://localhost:8000/api/v1/books/?page=1
Authorization: JWT {{ACCESS_TOKEN}}

### Get an specific book

GET http://localhost:8000/api/v1/books/1/
Authorization: JWT {{ACCESS_TOKEN}}

## Get categories of a book

GET http://localhost:8000/api/v1/books/1/categories/
Authorization: JWT {{ACCESS_TOKEN}}

### Update a book

PUT http://localhost:8000/api/v1/books/1/
Authorization: JWT {{ACCESS_TOKEN}}
Content-type: application/json

{}

### Change partially a book

PATCH http://localhost:8000/api/v1/books/1/
Content-type: application/json
Authorization: JWT {{ACCESS_TOKEN}}

{
  "title": "Python The Hard Way",
  "description": "The book 'The Python The Hard Way is a book to learn python"
}

### Create a new Book

POST http://localhost:8000/api/v1/books/
Content-type: application/json
Authorization: JWT {{ACCESS_TOKEN}}

{
  "title": "Core Java Volume I – Fundamentals",
  "description": "Core Java Volume I – Fundamentals is a Java reference book (Best book for Java)that offers a detailed explanation of various features of Core Java.",
  "edition": "11th Edtion",
  "language": "English",
  "page_number": 928,
  "publishier": "Pearson",
  "rating": 9.8,
  "available": true,
  "categories": [
    { "name": "Education" },
    { "name": "Programming" }
  ],
  "authors": [
    {
      "first_name": "Cay",
      "second_name": "Stephan",
      "paternal_last_name": "Horstmann",
      "country": "United States"
    }
  ]
}

### Delete an specific book

DELETE http://localhost:8000/api/v1/books/2/
Authorization: JWT {{ACCESS_TOKEN}}
