GET http://localhost:80/api/v1/profile/user/
Authorization: JWT {{ACCESS_TOKEN}}

PATCH http://localhost:80/api/v1/profile/update/
Authorization: JWT {{ACCESS_TOKEN}}

{
  "city": "New York",
  "adress_line_1": "kra l19",
  "adress_line_2": "apt 403",
  "state_provice_region": "New York",
  "zip_code": "23423",
  "phone": "2342342342",
  "country": "United States",
}
