### Get all carts in the database

GET http://localhost:8000/api/v1/carts/
Authorization: Bearer {{ACCESS_TOKEN}}
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxMTk3ODU4LCJpYXQiOjE2NjExMTE0NTgsImp0aSI6Ijg4MjkxMDViOWNkZDQ3ZmJiZDMyMjdmZTU0MmFkZGNmIiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJtcmZpeHRoaXMifQ.VagrDemCczqEzLsoASymKG11P_N92WHZoqe6TkZfMPk

### Get an specific cart

GET http://localhost:8000/api/v1/carts/4/
Authorization: Bearer {{ACCESS_TOKEN}}

### Add book to cart

POST http://localhost:8000/api/v1/carts/add-item/1/
Authorization: Bearer {{ACCESS_TOKEN}}

## delete an item from user cart

DELETE http://localhost:8000/api/v1/carts/remove-item/6/
Authorization: Bearer {{ACCESS_TOKEN}}
