### Get all carts in the database

GET http://localhost:8000/api/v1/carts/
Authorization: JWT {{ACCESS_TOKEN}}

### Get an specific cart

GET http://localhost:8000/api/v1/carts/1/
Authorization: JWT {{ACCESS_TOKEN}}

### Add book to cart

POST http://localhost:8000/api/v1/carts/add-item/
Authorization: JWT {{ACCESS_TOKEN}}
Content-type: application/json

{
  "book_id": 1,
  "quantity": 9
}

## delete an item from user cart

DELETE http://localhost:8000/api/v1/carts/remove-item/3/
Authorization: JWT {{ACCESS_TOKEN}}


GET http://localhost:8000/api/v1/carts/items/
Authorization: JWT {{ACCESS_TOKEN}}

PUT http://localhost:8000/api/v1/carts/update-item/
Authorization: JWT {{ACCESS_TOKEN}}

{
  "book_id": 1,
  "quantity": 33
}
