### Get all users in the database

GET http://localhost:80/api/v1/auth/users/
Authorization: JWT {{ACCESS_TOKEN}}

### Create a new user

POST http://localhost:80/api/v1/auth/users/
Content-type: application/json

{
  "username": "mrfixthis",
  "email": "fixthis@gmail.com",
  "password": "fix12345678",
  "re_password": "fix12345678",
  "first_name": "Unknown",
  "second_name": "World",
  "paternal_last_name": "InThe",
  "maternal_last_name": "Person"
}

### GET current user

GET http://localhost:80/api/v1/auth/users/me/
Authorization: JWT {{ACCESS_TOKEN}}


## Update cuerrent user

PATCH http://localhost:80/api/v1/auth/users/me/
Content-type: application/json
Authorization: JWT {{ACCESS_TOKEN}}

{
  "email": "yagua.db@gmail.com",
  "first_name": "Unknown",
  "maternal_last_name": "Person",
  "paternal_last_name": "InThe",
  "second_name": "World",
  "username": "yagua"
}

## Update partially current user

PATCH http://localhost:8000/api/v1/auth/users/me/
Content-type: application/json
Authorization: JWT {{ACCESS_TOKEN}}

{
  "is_active": true
}

## Delete an existing user

DELETE http://localhost:8000/api/v1/auth/users/me/
Authorization: JWT {{ACCESS_TOKEN}}
Content-type: application/json

{
  "current_password": "testpassword"
}

POST http://localhost:8000/api/v1/auth/users/activation/
Content-type: application/json

{
  "uid": "1",
  "token": "{{ACCESS_TOKEN}}"
}


# send email to restart the user password
POST http://localhost:80/api/v1/auth/users/reset_password/
Content-type: application/json

{
  "email": "email.test@gmail.com"
}

# confirm the password reset
POST http://localhost:80/api/v1/auth/users/reset_password_confirm/
Content-type: application/json

{
  "uid": "Mg",
  "token": "bd21bq-9680e9a670b28f5f692d1214fae9829d",
  "new_password": "fix12345",
  "re_new_password": "fix12345"
}
